// This file is auto-generated by scripts/generate-env.js
// DO NOT EDIT MANUALLY - Your changes will be overwritten!
// To change API keys, edit the .env file in the root directory

export const environment = {
  production: true,
  // API Keys para serviços externos
  weatherApiKey: 'YOUR_API_KEY_HERE'
};
