/**
 * Script para gerar arquivos environment.ts a partir de .env
 * Executa antes do build para injetar API keys
 */

const fs = require('fs');
const path = require('path');

// Caminhos dos arquivos
const envPath = path.join(__dirname, '..', '.env');
const envExamplePath = path.join(__dirname, '..', '.env.example');
const envDevPath = path.join(__dirname, '..', 'src', 'environments', 'environment.ts');
const envProdPath = path.join(__dirname, '..', 'src', 'environments', 'environment.prod.ts');

/**
 * Lê o arquivo .env e retorna um objeto com as variáveis
 */
function readEnvFile(filePath) {
  const env = {};
  
  if (!fs.existsSync(filePath)) {
    console.warn(`⚠️  Arquivo ${filePath} não encontrado. Usando valores padrão.`);
    return env;
  }

  const content = fs.readFileSync(filePath, 'utf-8');
  const lines = content.split('\n');

  for (const line of lines) {
    // Ignora comentários e linhas vazias
    const trimmedLine = line.trim();
    if (!trimmedLine || trimmedLine.startsWith('#')) {
      continue;
    }

    // Parse KEY=VALUE
    const equalIndex = trimmedLine.indexOf('=');
    if (equalIndex === -1) {
      continue;
    }

    const key = trimmedLine.substring(0, equalIndex).trim();
    const value = trimmedLine.substring(equalIndex + 1).trim();
    
    env[key] = value;
  }

  return env;
}

/**
 * Gera o conteúdo do arquivo environment.ts
 */
function generateEnvironmentFile(env, isProduction = false) {
  const weatherApiKey = env.WEATHER_API_KEY || 'YOUR_API_KEY_HERE';
  
  return `// This file is auto-generated by scripts/generate-env.js
// DO NOT EDIT MANUALLY - Your changes will be overwritten!
// To change API keys, edit the .env file in the root directory

export const environment = {
  production: ${isProduction},
  // API Keys para serviços externos
  weatherApiKey: '${weatherApiKey}'
};
`;
}

/**
 * Função principal
 */
function main() {
  console.log('🔧 Gerando arquivos environment...');

  // Lê o arquivo .env
  const env = readEnvFile(envPath);

  // Verifica se o .env existe, se não, cria a partir do .env.example
  if (!fs.existsSync(envPath)) {
    if (fs.existsSync(envExamplePath)) {
      console.log('📋 Arquivo .env não encontrado. Copiando .env.example para .env...');
      fs.copyFileSync(envExamplePath, envPath);
      console.log('✅ Arquivo .env criado!');
      console.log('⚠️  IMPORTANTE: Edite o arquivo .env na raiz do projeto e adicione suas API keys reais!');
      // Lê novamente após copiar
      Object.assign(env, readEnvFile(envPath));
    } else {
      // Cria .env.example se não existir
      console.log('📋 Criando .env.example...');
      const exampleContent = `# API Keys - Template
# Copie este arquivo para .env e preencha com suas keys reais
# NUNCA commite o arquivo .env com keys reais!

# OpenWeatherMap API Key
# Obtenha em: https://home.openweathermap.org/users/sign_up
WEATHER_API_KEY=YOUR_API_KEY_HERE
`;
      fs.writeFileSync(envExamplePath, exampleContent, 'utf-8');
      console.log('✅ .env.example criado');
      
      // Agora copia para .env
      console.log('📋 Copiando .env.example para .env...');
      fs.copyFileSync(envExamplePath, envPath);
      console.log('✅ Arquivo .env criado!');
      console.log('⚠️  IMPORTANTE: Edite o arquivo .env na raiz do projeto e adicione suas API keys reais!');
      Object.assign(env, readEnvFile(envPath));
    }
  }

  // Gera environment.ts (desenvolvimento)
  const devContent = generateEnvironmentFile(env, false);
  fs.writeFileSync(envDevPath, devContent, 'utf-8');
  console.log('✅ environment.ts gerado');

  // Gera environment.prod.ts (produção)
  const prodContent = generateEnvironmentFile(env, true);
  fs.writeFileSync(envProdPath, prodContent, 'utf-8');
  console.log('✅ environment.prod.ts gerado');

  // Verifica se há keys não configuradas
  if (env.WEATHER_API_KEY === 'YOUR_API_KEY_HERE' || !env.WEATHER_API_KEY) {
    console.warn('⚠️  ATENÇÃO: WEATHER_API_KEY não configurada no .env');
    console.warn('⚠️  Edite o arquivo .env na raiz do projeto para adicionar sua API key');
  } else {
    console.log('✅ API keys configuradas');
  }

  console.log('✨ Concluído!');
}

// Executa o script
main();

